version: '3.8'
services:

  psql:
    restart: always
    image: postgres:13
    container_name: psql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: mySuperPass
      POSTGRES_DB: test